### ISSUE TITLE
[feat] Allow progress to exceed 100%

### ISSUE THREAD

**Issue by erinoerin** [adampage/figma-progress-bar#2]
Currently the the progress bar is limited to 100% (e.g. 10/10). Given that we make goals, but often know or hope we'll exceed them, for the purpose of tracking actual progress, it would be helpful if the progress bar could facilitate the case when we do exceed our goals. Thank you for your consideration.

**Comment by adampage** [comment]
Thanks, @erinoerin!  I’ve added an initial concept for goal-exceeding in [Version 2 of the widget](https://www.figma.com/community/widget/1129311231149791125/Progress-Bar#:~:text=Version%202%20on%20August%207%2C%202022).  Please have a look and let me know what you think? 😄   Here’s a quick demo:

![A user demonstrates the new surplus capability of the Progress Bar widget.](https://user-images.githubusercontent.com/1395630/183483872-082d9d46-053d-4392-8623-09607011cbd7.gif)
